export const SYSTEM_ICONS = {
    loading: require('@/assets/icons/system/loading.png'),
    habit: require('@/assets/icons/system/habit-icon.png'),
    path: require('@/assets/icons/system/path-icon.png'),
    path2: require('@/assets/icons/system/path-icon2.png'),
    quest: require('@/assets/icons/system/quest-icon.png'),
    profile: require('@/assets/icons/system/profile-icon.png'),
    more: require('@/assets/icons/system/more-icon.png'),
    back: require('@/assets/icons/system/back.png'),
    list: require('@/assets/icons/system/list.png'),
    reward: require('@/assets/icons/system/sparkle-fill.png'),
    journal: require('@/assets/icons/system/journal-icon.png'),
    settings: require('@/assets/icons/system/settings-icon.png'),
    sortLeft: require('@/assets/icons/system/sort-left.png'),
    sortRight: require('@/assets/icons/system/sort-right.png'),
    clock: require('@/assets/icons/system/clock.png'),
    repeat: require('@/assets/icons/system/repeat.png'),
    calendar: require('@/assets/icons/system/calendar.png'),
    dots: require('@/assets/icons/system/dots.png'),
    location: require('@/assets/icons/system/location-icon.png'),
};